server:
  port: 9002
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  application:
    name: order-service
  lifecycle: # `server.shutdown` is a ` graceful ` value by default
    timeout-per-shutdown-phase: 15s # 30s is default
