name: Commit Stage
on: push
jobs:
  build:
    name: Build and Test ${{ matrix.project }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      security-events: write
    strategy:
      fail-fast: true
      matrix:
        project:
          - Chapter03/catalog-service
          - Chapter04/catalog-service
          - Chapter04/config-service
          - Chapter05/catalog-service
          - Chapter05/config-service
          - Chapter06/catalog-service
          - Chapter06/config-service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 26
          cache: gradle
      - name: Code vulnerability scanning
        uses: anchore/scan-action@v7
        id: scan
        with:
          path: ${{ github.workspace }}
          fail-build: true
          severity-cutoff: high
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v4
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Build, unit tests, and integration tests
        working-directory: ${{ matrix.project }}
        run: |
          chmod +x gradlew
          ./gradlew build
